const spaces = [
  ['01', 'Museums & culture', 'A new perspective, every visit. Spaces to encounter art, history, and ideas that stay with you.', 'Discover'],
  ['02', 'Studios & making', 'Room to follow your curiosity. Make something with your hands, find your medium, and develop your practice.', 'Create'],
  ['03', 'Wellness & restoration', 'A little space to return to yourself. Move, breathe, and build rituals that nourish your everyday life.', 'Restore'],
  ['04', 'Creative workspaces', 'Good work starts in an inspiring place. Find your focus alongside people building something meaningful.', 'Connect'],
  ['05', 'Vocational schools', 'Wisdom through doing. From material craft to hardware fabrication, turn an idea into something real.', 'Learn'],
  ['06', 'Technology hubs', 'A home for the next possibility. Explore tools, exchange knowledge, and bring new ideas to life.', 'Build'],
];
export default function Home() {
  return <main id="top">
    <header className="nav"><a className="wordmark" href="#top" aria-label="Eden Cities home">eden<span>CITIES</span></a><nav aria-label="Main navigation"><a href="#philosophy">The idea</a><a href="#spaces">Our spaces</a><a href="#membership">Membership <span>↗</span></a></nav></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> A WORLD OF POSSIBILITY</p><h1>A garden where<br/>wisdom <em>grows.</em></h1><p className="intro">Places to be curious. Space to become.<br/>One membership to enrich your life, across the world.</p><a className="button" href="#spaces">Explore the world of Eden <span>↗</span></a><div className="hero-bottom"><span>ROOTED IN CURIOSITY. OPEN TO THE WORLD.</span><a href="#philosophy" aria-label="Discover the Eden philosophy">↓</a></div></div><div className="hero-image"><img src="https://www.architectura.com/americandream/application/files/thumbnails/large/4016/0872/8747/hacienda_petac_yucatan.jpg" alt="A lush garden courtyard with stone arches and a reflecting pool"/><div className="image-label"><span>A DIFFERENT WAY TO BELONG</span><span>01 / EDEN</span></div></div></section>
    <div className="ribbon"><span>One membership.</span><i>✳</i><span>Global access.</span><i>✳</i><span>Endless possibility.</span><i>✳</i></div>
    <section id="philosophy" className="philosophy section"><p className="eyebrow">THE EDEN PHILOSOPHY</p><div><h2>A richer life.<br/><em>By design.</em></h2><div className="philosophy-body"><p>EDEN stands for <strong>Experiences Designed to Enrich and Nourish.</strong> A growing vision for places that feed the mind, move the body, and awaken the imagination.</p><p>From a quiet moment in a museum to a breakthrough in a workshop, we believe growth happens when you have space to explore. Eden brings those spaces together.</p></div></div></section>
    <section id="spaces" className="spaces section"><div className="section-heading"><div><p className="eyebrow">MANY WAYS TO GROW</p><h2>Follow your curiosity.</h2></div><p>Six worlds of experience.<br/>One connected way of life.</p></div><div className="space-grid">{spaces.map(([n,title,description,verb])=><article className="space" key={n}><div className="space-top"><span>{n}</span><span>{verb} ↗</span></div><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="global section"><p className="eyebrow">LOCALLY ROOTED. GLOBALLY CONNECTED.</p><h2>A different city.<br/>The same sense of <em>belonging.</em></h2><p>Our vision is a world of Eden spaces: shaped by the character of each city, connected by the same thoughtful experience. Wherever life takes you, find a place to keep growing.</p><span className="small-note">Our global garden is taking shape. Cities and opening details to come.</span></section>
    <section id="membership" className="membership section"><div><p className="eyebrow">THE EDEN MEMBERSHIP</p><h2>Your world,<br/><em>opened up.</em></h2><p>One membership. Global access.<br/>A life with more room to grow.</p></div><div className="membership-card"><span className="eyebrow">ONE MEMBERSHIP. ALL OF EDEN.</span><div className="price">$1,000 <span>/ month</span></div><p>Experiences designed to enrich and nourish.</p><ul><li>Access across the Eden Cities network</li><li>Culture, creativity, wellness, and work</li><li>Hands-on learning and new possibilities</li><li>A familiar experience across the world</li></ul><a href="#details" className="button pale">Explore membership details <span>↓</span></a></div></section>
    <section id="details" className="faq section"><p className="eyebrow">A LITTLE MORE TO KNOW</p><div><details><summary>What is Eden Cities?<span>+</span></summary><p>Eden Cities is a vision for a global network of museums, studios, wellness centers, creative workspaces, vocational schools, and technology hubs, connected through one membership.</p></details><details><summary>What does membership cost?<span>+</span></summary><p>The proposed Eden membership is $1,000 per month for global access across the network. Detailed access terms and the enrollment process will be shared when membership opens.</p></details><details><summary>Which cities can I visit?<span>+</span></summary><p>The global network is being developed. Confirmed locations, participating spaces, and opening dates have not yet been announced.</p></details></div></section>
    <footer><a className="wordmark" href="#top">eden<span>CITIES</span></a><p>Experiences Designed to Enrich and Nourish.</p><a href="#top">Keep growing. ↑</a></footer>
  </main>;
}
